(() => {
  const nativeDate = Date; const nativeFunction = Function; const now = __cff_now_ms;
  function fixedDate() { const calledWithNew = this instanceof fixedDate; if (!calledWithNew) return new nativeDate(now).toString(); if (arguments.length === 0) return new nativeDate(now); if (arguments.length === 1) return new nativeDate(arguments[0]); if (arguments.length === 2) return new nativeDate(arguments[0], arguments[1]); if (arguments.length === 3) return new nativeDate(arguments[0], arguments[1], arguments[2]); if (arguments.length === 4) return new nativeDate(arguments[0], arguments[1], arguments[2], arguments[3]); if (arguments.length === 5) return new nativeDate(arguments[0], arguments[1], arguments[2], arguments[3], arguments[4]); if (arguments.length === 6) return new nativeDate(arguments[0], arguments[1], arguments[2], arguments[3], arguments[4], arguments[5]); return new nativeDate(arguments[0], arguments[1], arguments[2], arguments[3], arguments[4], arguments[5], arguments[6]); }
  fixedDate.prototype = nativeDate.prototype; fixedDate.now = () => now; fixedDate.parse = nativeDate.parse; fixedDate.UTC = nativeDate.UTC; globalThis.Date = fixedDate;
  const forbidden = function () { throw new TypeError("dynamic code evaluation is not supported"); }; globalThis.eval = forbidden; globalThis.Function = forbidden; nativeFunction.prototype.constructor = forbidden;
  const hiddenGlobals = ["process", "fetch", "XMLHttpRequest", "WebSocket", "Deno", "Bun", "WebAssembly", "Atomics", "SharedArrayBuffer", "BigInt", "BigInt64Array", "BigUint64Array", "Proxy", "Map", "Set", "WeakMap", "WeakSet", "FinalizationRegistry", "queueMicrotask", "setTimeout", "setImmediate", "setInterval", "clearTimeout", "clearInterval", "Blob", "File"];
  hiddenGlobals.forEach((name) => { try { delete globalThis[name]; } catch (_) {} });
  if (typeof TextEncoder === "undefined") { function CompatTextEncoder() { this.encoding = "utf-8"; } CompatTextEncoder.prototype.encode = function (value) { return Buffer.from(String(value), "utf8"); }; CompatTextEncoder.prototype.encodeInto = function (value, destination) { const bytes = Buffer.from(String(value), "utf8"); const written = Math.min(bytes.length, destination.length); for (let index = 0; index < written; index++) destination[index] = bytes[index]; return { read: written === bytes.length ? String(value).length : 0, written }; }; globalThis.TextEncoder = CompatTextEncoder; }
  if (typeof TextDecoder === "undefined") { function CompatTextDecoder() { this.encoding = "utf-8"; this.fatal = false; this.ignoreBOM = false; } CompatTextDecoder.prototype.decode = function (value) { return Buffer.from(value || new Uint8Array()).toString("utf8"); }; globalThis.TextDecoder = CompatTextDecoder; }
  const consoleLog = __cff_console_log; globalThis.console = Object.freeze({ log: function (value) { if (arguments.length !== 1) throw new TypeError("console.log() requires exactly one argument"); return consoleLog(value); } });
  globalThis.require = (name) => { if (name === "crypto") return globalThis.__cff_crypto; if (name === "querystring") return globalThis.__cff_querystring; if (name === "cloudfront") return globalThis.__cff_cloudfront; throw new Error("module is not available: " + name); };
  [fixedDate, nativeFunction, Object, String, Number, Math, Array, ArrayBuffer, Promise, Symbol, RegExp, JSON, typeof TextEncoder === "undefined" ? null : TextEncoder, typeof TextDecoder === "undefined" ? null : TextDecoder].forEach((value) => { if (value) { try { Object.freeze(value); if (value.prototype) Object.freeze(value.prototype); } catch (_) {} } });
  globalThis.__cff_event = undefined;
})();
