pub const SUPPORTED_MODULES: &[&str] = &["crypto", "querystring", "cloudfront"];

pub const UNSUPPORTED_GLOBALS: &[&str] = &[
    "process",
    "fetch",
    "XMLHttpRequest",
    "WebSocket",
    "Deno",
    "Bun",
    "WebAssembly",
    "Atomics",
    "SharedArrayBuffer",
    "BigInt",
    "BigInt64Array",
    "BigUint64Array",
    "Proxy",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "FinalizationRegistry",
    "queueMicrotask",
    "setTimeout",
    "setImmediate",
    "setInterval",
    "clearTimeout",
    "clearInterval",
];

pub const TIMER_GLOBALS: &[&str] = &[
    "setTimeout",
    "setImmediate",
    "setInterval",
    "clearTimeout",
    "clearInterval",
    "queueMicrotask",
];

pub const STATIC_MEMBERS: &[(&str, &[&str])] = &[
    (
        "Object",
        &[
            "create",
            "defineProperties",
            "defineProperty",
            "freeze",
            "getOwnPropertyDescriptor",
            "getOwnPropertyDescriptors",
            "getOwnPropertyNames",
            "getPrototypeOf",
            "isExtensible",
            "isFrozen",
            "isSealed",
            "keys",
            "preventExtensions",
            "seal",
            "assign",
            "entries",
            "values",
        ],
    ),
    ("Float32Array", &["from", "of"]),
    ("Float64Array", &["from", "of"]),
    ("Int8Array", &["from", "of"]),
    ("Int16Array", &["from", "of"]),
    ("Int32Array", &["from", "of"]),
    ("Uint8Array", &["from", "of"]),
    ("Uint8ClampedArray", &["from", "of"]),
    ("Uint16Array", &["from", "of"]),
    ("Uint32Array", &["from", "of"]),
    ("String", &["fromCharCode", "fromCodePoint"]),
    ("TextDecoder", &[]),
    ("TextEncoder", &[]),
    (
        "Number",
        &[
            "EPSILON",
            "MAX_SAFE_INTEGER",
            "MIN_SAFE_INTEGER",
            "MAX_VALUE",
            "MIN_VALUE",
            "NaN",
            "NEGATIVE_INFINITY",
            "POSITIVE_INFINITY",
            "isFinite",
            "isInteger",
            "isNaN",
            "isSafeInteger",
            "parseInt",
            "parseFloat",
        ],
    ),
    (
        "Math",
        &[
            "E", "LN10", "LN2", "LOG10E", "LOG2E", "PI", "SQRT1_2", "SQRT2", "abs", "acos",
            "acosh", "asin", "asinh", "atan", "atan2", "atanh", "cbrt", "ceil", "clz32", "cos",
            "cosh", "exp", "expm1", "floor", "fround", "hypot", "imul", "log", "log1p", "log2",
            "log10", "max", "min", "pow", "random", "round", "sign", "sinh", "sin", "sqrt", "tan",
            "tanh", "trunc",
        ],
    ),
    ("Array", &["isArray", "of"]),
    ("ArrayBuffer", &["isView"]),
    (
        "Promise",
        &["all", "allSettled", "any", "reject", "resolve", "race"],
    ),
    ("Symbol", &["for", "keyFor"]),
    ("Date", &["parse", "UTC", "now"]),
    (
        "Buffer",
        &[
            "alloc",
            "allocUnsafe",
            "byteLength",
            "compare",
            "concat",
            "from",
            "isBuffer",
            "isEncoding",
        ],
    ),
    ("Function", &[]),
    ("RegExp", &[]),
    ("JSON", &["parse", "stringify"]),
    ("globalThis", &[]),
];

pub const PROTOTYPE_MEMBERS: &[(&str, &[&str])] = &[
    (
        "Object",
        &[
            "hasOwnProperty",
            "isPrototypeOf",
            "propertyIsEnumerable",
            "toString",
            "valueOf",
            "is",
            "setPrototypeOf",
        ],
    ),
    ("TextDecoder", &["decode", "encoding", "fatal", "ignoreBOM"]),
    ("TextEncoder", &["encode", "encodeInto"]),
    (
        "String",
        &[
            "charAt",
            "concat",
            "indexOf",
            "lastIndexOf",
            "match",
            "replace",
            "search",
            "slice",
            "split",
            "substr",
            "substring",
            "toLowerCase",
            "trim",
            "toUpperCase",
            "codePointAt",
            "endsWith",
            "includes",
            "repeat",
            "startsWith",
            "padStart",
            "padEnd",
            "trimStart",
            "trimEnd",
            "replaceAll",
        ],
    ),
    ("Number", &["toExponential", "toFixed", "toPrecision"]),
    (
        "Array",
        &[
            "concat",
            "every",
            "filter",
            "forEach",
            "indexOf",
            "join",
            "lastIndexOf",
            "map",
            "pop",
            "push",
            "reduce",
            "reduceRight",
            "reverse",
            "shift",
            "slice",
            "some",
            "sort",
            "splice",
            "unshift",
            "copyWithin",
            "fill",
            "find",
            "findIndex",
            "includes",
        ],
    ),
    (
        "TypedArray",
        &[
            "copyWithin",
            "every",
            "fill",
            "filter",
            "find",
            "findIndex",
            "forEach",
            "includes",
            "indexOf",
            "join",
            "lastIndexOf",
            "map",
            "reduce",
            "reduceRight",
            "reverse",
            "some",
            "set",
            "slice",
            "sort",
            "subarray",
            "toString",
        ],
    ),
    ("ArrayBuffer", &["slice"]),
    ("Promise", &["catch", "finally", "then"]),
    (
        "DataView",
        &[
            "getFloat32",
            "getFloat64",
            "getInt16",
            "getInt32",
            "getInt8",
            "getUint16",
            "getUint32",
            "getUint8",
            "setFloat32",
            "setFloat64",
            "setInt16",
            "setInt32",
            "setInt8",
            "setUint16",
            "setUint32",
            "setUint8",
        ],
    ),
    (
        "RegExp",
        &[
            "exec",
            "test",
            "toString",
            "global",
            "ignoreCase",
            "multiline",
            "source",
            "sticky",
            "flags",
            "lastIndex",
        ],
    ),
    ("Function", &["apply", "bind", "call"]),
    ("Date", &[]),
    (
        "Buffer",
        &[
            "compare",
            "copy",
            "equals",
            "fill",
            "includes",
            "indexOf",
            "lastIndexOf",
            "readInt8",
            "readIntBE",
            "readInt16BE",
            "readInt32BE",
            "readIntLE",
            "readInt16LE",
            "readInt32LE",
            "readUInt8",
            "readUIntBE",
            "readUInt16BE",
            "readUInt32BE",
            "readUIntLE",
            "readUInt16LE",
            "readUInt32LE",
            "readDoubleBE",
            "readDoubleLE",
            "readFloatBE",
            "readFloatLE",
            "subarray",
            "swap16",
            "swap32",
            "swap64",
            "toJSON",
            "toString",
            "write",
            "writeInt8",
            "writeIntBE",
            "writeInt16BE",
            "writeInt32BE",
            "writeIntLE",
            "writeInt16LE",
            "writeInt32LE",
            "writeUInt8",
            "writeUIntBE",
            "writeUInt16BE",
            "writeUInt32BE",
            "writeUIntLE",
            "writeUInt16LE",
            "writeUInt32LE",
            "writeDoubleBE",
            "writeDoubleLE",
            "writeFloatBE",
            "writeFloatLE",
            "buffer",
            "byteOffset",
            "length",
        ],
    ),
];

pub fn static_member_allowed(base: &str, member: &str) -> bool {
    (member == "prototype"
        && (PROTOTYPE_MEMBERS.iter().any(|(name, _)| *name == base) || base.ends_with("Array")))
        || base == "globalThis"
        || STATIC_MEMBERS
            .iter()
            .find(|(name, _)| *name == base)
            .is_some_and(|(_, members)| members.contains(&member))
}

pub fn prototype_member_allowed(base: &str, member: &str) -> bool {
    let members = PROTOTYPE_MEMBERS
        .iter()
        .find(|(name, _)| *name == base)
        .map(|(_, members)| *members)
        .or_else(|| {
            base.ends_with("Array")
                .then(|| {
                    PROTOTYPE_MEMBERS
                        .iter()
                        .find(|(name, _)| *name == "TypedArray")
                        .map(|(_, members)| *members)
                })
                .flatten()
        });
    members.is_some_and(|members| members.is_empty() || members.contains(&member))
}
