name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  RUST_VERSION: 1.96.0

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust toolchain
        run: rustup toolchain install "${RUST_VERSION}" --profile minimal --no-self-update

      - name: Test
        run: cargo +"${RUST_VERSION}" test --locked
